### ISSUE TITLE
Add "modules" tab that shows status of internal modules

### ISSUE THREAD

**Issue by NobleDraconian** [iaincollins/icarus#44]
Much like the in-game "modules" tab, it would be awesome if we could have a "modules" tab in icarus that lists our internal modules & their status (health being the most important one). This is extremely useful while in combat! While fighting thargoids, I'm often overheating temporarily and like keeping an eye on my modules to make sure they're above 75% health.

**Comment by iaincollins** [comment]
Sorry, this got auto-closed.

Yeah agree! I actually did have something like this in an early version but it turns out that Elite Dangerous doesn't write to the file that contains that data very often and it's very often out of sync with what is actually happening in game, which is a shame.

So I it sees I can't do that one for now, sadly, as the official API doesn't fully support this use case. :-(

**Comment by NobleDraconian** [comment]
Aw, that's unfortunate :(
